import { ChatPlugin } from "@/components/chat-pluggin";
import { Header } from "@/components/header";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { fontsClass } from "@/fonts";
import { ModalProvider } from "@/providers/modal-provider";
import { ToastProvider } from "@/providers/toast-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(fontsClass, "bg-color_choklet font-lemon")}>
        <Header />
        {children}
        <ChatPlugin />
        <ModalProvider />
        <ToastProvider />
      </body>
    </html>
  );
}
